# Use container based builds
sudo: false

script: ./gradlew build testReleaseUnitTest connectedAndroidTest

# Lang type
language: android

#- echo yes | android update sdk -a -t tools,platform-tools,extra-android-support,extra-android-m2repository,android-19,build-tools-19.1.0,extra-google-google_play_services,extra-google-m2repository --force --no-ui

android:
  components:
    # latest version of the tools
    - tools
    - platform-tools

    # build tools version
    - build-tools-23.0.2

    # The SDK Version
    - android-23

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

    # devices
    - sys-img-armeabi-v7a-android-21

jdk: oraclejdk8

#notifications:
#  email:
#    - dev@code-troopers.com

# Emulator Management: Create, Start and Wait
before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &